// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// 'use client';
// import { usePathname } from "next/navigation";
// import Sidebar from "./components/Sidebar";

// export default function Layout({ children }) {
//   const pathname = usePathname();
//   const noSidebarRoutes = ["/login", "/register"];

//   // Exclude sidebar for login and registration pages
//   if (noSidebarRoutes.includes(pathname)) {
//     return <>{children}</>;
//   }

//   return (
//     <div className="flex h-screen">
//       <Sidebar />
//       <main className="flex-1">{children}</main>
//     </div>
//   );
// }

// 'use client';
// import { usePathname } from "next/navigation";
// import Sidebar from "./components/Sidebar";
// import { useState } from "react";

// export default function Layout({ children }) {
//   const pathname = usePathname();
//   const noSidebarRoutes = ["/login", "/register"];

//   // Define chat state and handlers for Sidebar
//   const [chats, setChats] = useState([
//     {
//       id: 1,
//       name: "John Doe",
//       lastMessage: "Hey there!",
//       unread: 2,
//       image: "/travel.png",
//       messages: [
//         { id: 1, sender: "John Doe", text: "Hey there! How's it going?", time: "10:15 AM" },
//         { id: 2, sender: "You", text: "Hi John! I'm doing well, thank you. How about you?", time: "10:16 AM" },
//         { id: 3, sender: "John Doe", text: "I'm good, just getting some work done.", time: "10:18 AM" },
//       ],
//     },
//     {
//       id: 2,
//       name: "Jane Smith",
//       lastMessage: "See you tomorrow!",
//       unread: 0,
//       image: "/travel.png",
//       messages: [
//         { id: 1, sender: "You", text: "Hey Jane, are we still on for tomorrow?", time: "2:45 PM" },
//         { id: 2, sender: "Jane Smith", text: "Yes, absolutely! See you tomorrow!", time: "2:46 PM" },
//       ],
//     },
//   ]);
//   const [activeChat, setActiveChat] = useState(null);

//   // Exclude sidebar for login and registration pages
//   if (noSidebarRoutes.includes(pathname)) {
//     return <>{children}</>;
//   }

//   return (
//     <div className="flex h-screen">
//       <Sidebar
//         chats={chats}
//         onChatSelect={setActiveChat}
//       />
//       <main className="flex-1">{children}</main>
//     </div>
//   );
// }
// 'use client';
// import { usePathname } from "next/navigation";
// import Sidebar from "./components/Sidebar";
// import { useState } from "react";

// export default function Layout({ children }) {
//   const pathname = usePathname();
//   const noSidebarRoutes = ["/login", "/register"];

//   // Define chat state and handlers for Sidebar
//   const [chats, setChats] = useState([
//     {
//       id: 1,
//       name: "John Doe",
//       lastMessage: "Hey there!",
//       unread: 2,
//       image: "/travel.png",
//       messages: [
//         { id: 1, sender: "John Doe", text: "Hey there! How's it going?", time: "10:15 AM" },
//         { id: 2, sender: "You", text: "Hi John! I'm doing well, thank you. How about you?", time: "10:16 AM" },
//         { id: 3, sender: "John Doe", text: "I'm good, just getting some work done.", time: "10:18 AM" },
//       ],
//     },
//     {
//       id: 2,
//       name: "Jane Smith",
//       lastMessage: "See you tomorrow!",
//       unread: 0,
//       image: "/travel.png",
//       messages: [
//         { id: 1, sender: "You", text: "Hey Jane, are we still on for tomorrow?", time: "2:45 PM" },
//         { id: 2, sender: "Jane Smith", text: "Yes, absolutely! See you tomorrow!", time: "2:46 PM" },
//       ],
//     },
//   ]);
//   const [activeChat, setActiveChat] = useState(null);

//   // Exclude sidebar for login and registration pages
//   if (noSidebarRoutes.includes(pathname)) {
//     return <>{children}</>;
//   }

//   return (
//     <div className="flex h-screen bg-gray-100">
//       <Sidebar
//         chats={chats}
//         onChatSelect={setActiveChat}
//       />
//       <main className="flex-1">{children}</main>
//     </div>
//   );
// }
import './globals.css'; // Global styles
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Your App',
  description: 'Description of your app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}





